package controller.subject;

import dao.CategoryDAO;
import dao.SubjectDAO;
import dao.SubjectDescriptionImageDAO;
import dao.UserDAO;
import dto.UserDTO;
import entity.Category;
import entity.Subject;
import entity.SubjectDescriptionImage;
import entity.User;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;
import util.ImageUploader;

import java.io.IOException;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@WebServlet(name = "CreateSubjectServlet", urlPatterns = {"/management/subject/create"})
@MultipartConfig(
        fileSizeThreshold = 1024 * 1024,         // 1MB (bộ nhớ tạm)
        maxFileSize = 10 * 1024 * 1024,          // 10MB cho mỗi file
        maxRequestSize = 100 * 1024 * 1024       // 100MB cho toàn bộ form
)
public class CreateSubjectServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        UserDTO user = (UserDTO) session.getAttribute("user");

        if (user == null) {
            response.sendRedirect(request.getContextPath() + "/account/login");
            return;
        }
        CategoryDAO categoryDAO = new CategoryDAO();
        UserDAO userDAO = new UserDAO();

        List<Category> categories = categoryDAO.getAllCategory();
        ArrayList<User> experts = userDAO.getAllExpert();

        request.setAttribute("categories", categories);
        request.setAttribute("experts", experts);
        request.getRequestDispatcher("/subject/subject_create.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        SubjectDAO subjectDAO = new SubjectDAO();
        List<Subject> subjects = subjectDAO.getAllSubjectsWithoutID();
        String categoryIdParam = request.getParameter("subjectCategory");
        String ownerIdParam = request.getParameter("owner");
        String name = request.getParameter("subjectName");
        String status = request.getParameter("status");
        String rawDescription = request.getParameter("subjectDescription");
        String subjectDescription = rawDescription != null ? rawDescription.replace("\n", "\\n") : "";
        String tagLine = request.getParameter("tagLine");
        boolean isFeatured = request.getParameter("featured") != null;
        Part thumbnailPart = request.getPart("thumbnail");

        int categoryId = 0;
        int ownerId = 0;

        try {
            categoryId = Integer.parseInt(categoryIdParam);
            if (ownerIdParam != null && !ownerIdParam.isEmpty()) {
                ownerId = Integer.parseInt(ownerIdParam);
            } else {
                // If no owner specified, use current user as owner
                User currentUser = (User) request.getSession().getAttribute("user");
                if (currentUser != null) {
                    ownerId = currentUser.getId();
                }
            }
        } catch (NumberFormatException e) {
            System.out.println("Number format exception: " + e.getMessage());
            session.setAttribute("toastNotification", "Invalid number format in form data.");
            response.sendRedirect("create");
            return;
        }

        // Validate required fields
        if (name == null || name.trim().isEmpty() ||
                categoryId == 0 || ownerId == 0 ||
                subjectDescription == null || subjectDescription.trim().isEmpty() ||
                tagLine == null || tagLine.trim().isEmpty() ||
                thumbnailPart == null || thumbnailPart.getSize() == 0) {

            session.setAttribute("toastNotification", "All required fields must be filled.");
            response.sendRedirect("create");
            return;
        }
        for(Subject subject: subjects){
            if(subject.getName().equals(name)){
                session.setAttribute("toastNotification", "Subject name is existed");
                response.sendRedirect("create");
                return;
            }
        }


        Subject subject = new Subject();

        // Set subject properties (ID will be auto-generated by database)
        subject.setName(name.trim());
        subject.setLongDescription(subjectDescription.trim());
        subject.setTagLine(tagLine.trim());
        subject.setFeaturedSubject(isFeatured);
        subject.setPublished(status != null && status.equals("Published"));
        subject.setCategoryId(categoryId);
        subject.setOwnerId(ownerId);
        subject.setUpdateDate(LocalDateTime.now());

        // Handle thumbnail upload
        String thumbnailName = null;
        if (thumbnailPart.getSize() > 0) {
            String thumbnailDirectory = getServletContext().getRealPath("assets/images/thumbnail/subject");
            String thumbnailOriginalName = thumbnailPart.getSubmittedFileName();
            String extension = thumbnailOriginalName.substring(thumbnailOriginalName.lastIndexOf("."));
            thumbnailName = "subject_" + System.currentTimeMillis() + extension;

            try {
                ImageUploader.saveImage(thumbnailDirectory, thumbnailName, thumbnailPart);
                subject.setThumbnail(thumbnailName);
            } catch (Exception e) {
                System.out.println("Error saving thumbnail: " + e.getMessage());
                session.setAttribute("toastNotification", "Error uploading thumbnail image.");
                response.sendRedirect("create");
                return;
            }
        }

        int newSubjectId = subjectDAO.insertSubject(subject);
        if(newSubjectId==-1){
            session.setAttribute("toastNotification", "Failed to create subject. Please try again.");
            response.sendRedirect("create");
            return;
        }
        // Handle subject description images
        SubjectDescriptionImageDAO subjectDescriptionImageDAO = new SubjectDescriptionImageDAO();
        String descriptionImageDirectory = getServletContext().getRealPath("assets/images/subject_description");

        // Get all parts from form
        Collection<Part> imageParts = request.getParts();
        List<Part> descriptionImageParts = new ArrayList<>();

        // Get all images with name = "subjectDescriptionImageInput"
        for (Part part : imageParts) {
            if ("subjectDescriptionImageInput".equals(part.getName()) && part.getSize() > 0) {
                descriptionImageParts.add(part);
            }
        }

        // Get all captions
        String[] captions = request.getParameterValues("subjectDescriptionImageCaption");
        List<String> descriptionImageCaptions = new ArrayList<>();
        if (captions != null) {
            for (String caption : captions) {
                descriptionImageCaptions.add(caption != null ? caption.trim() : "");
            }
        }
        long MAX_FILE_SIZE = 10 * 1024 * 1024;
        // Process description images
        for (int i = 0; i < descriptionImageParts.size(); i++) {
            Part imagePart = descriptionImageParts.get(i);
            String caption = i < descriptionImageCaptions.size() ? descriptionImageCaptions.get(i) : "";

            if (imagePart.getSize() > 0) {
                try {
                    String originalName = imagePart.getSubmittedFileName();
                    String extension = originalName.substring(originalName.lastIndexOf("."));
                    String newImageName = "subject_desc_" + newSubjectId + "_" + Instant.now().toEpochMilli() + extension;

                    // Save image file
                    ImageUploader.saveImage(descriptionImageDirectory, newImageName, imagePart);

                    // Create database record
                    SubjectDescriptionImage newImage = new SubjectDescriptionImage();
                    newImage.setSubjectId(newSubjectId);
                    newImage.setUrl(newImageName);
                    newImage.setCaption(caption);

                    boolean imageInserted = subjectDescriptionImageDAO.add(newImage);
                    if (imageInserted) {
                        System.out.println("Added new description image: " + newImageName);
                    } else {
                        System.out.println("Failed to add description image to database: " + newImageName);
                    }
                } catch (Exception e) {
                    System.out.println("Error processing description image " + i + ": " + e.getMessage());
                }
            }
        }

        // Set success message and redirect

        session.setAttribute("toastNotification", "Subject has been created successfully.");
        response.sendRedirect("create");
    }
}